### ISSUE TITLE
Issue for Bondfire // Solo Rugs

### ISSUE THREAD

**Issue by Johnsalzarulo** [withbetterco/guidebook#4]
Website: 
[https://www.solorugs.com/](https://www.solorugs.com/)

**Overview Video:** 
https://www.useloom.com/share/29c56dd7cf4c455aa3f161eec7306606

Needed Changes: 
- [x] When clicking on + More in the sidebar, it expands the full list of filters with a fixed height and overflow scroll. We want to remove that fixed height so you can see all options without scrolling
- [x] Hide Search box from sidebar filter groups (shows up when you click + More) Hide Hide X button from sidebar
- [x] Force dimensions in product title to drop to second line on the product tile component. (Split at -) (Reference our old collection style here: https://www.solorugs.com/collections/all/color-blue)
- [x] Hide Hide X button from sidebar

[https://dashboard.findify.io/](https://dashboard.findify.io/)

username: daniel@bondfireinc.com
password: 6Z.LfAZeHqL8HR

[Guide on using the dev tools](https://developers.findify.io/docs/using-the-findify-react-devtools)

Important for reference: [All of the original components can be found here](https://github.com/findify/findify-js/tree/develop/packages/react-components/src/components)

**Video Showing the specific file issue I was mentioning:** 
This issue was holding me up as I was trying to write changes last night: 

https://www.useloom.com/share/bee1bff6d9d24b20a1e61285f896306b

**Comment by Johnsalzarulo** [comment]
Also - Just realized I missed one of the deliverables "Hide Hide X button from sidebar" I added it above. 

<img width="713" alt="screen shot 2018-10-26 at 12 34 31 pm" src="https://user-images.githubusercontent.com/3476109/47588601-901d8c00-d91b-11e8-92d8-bb44e7f2a1ce.png">

**Comment by PolarisTLX** [comment]
I believe this addresses the third task:   `Force dimensions in product title to drop to second line on the product tile component. ` ?

(This was done by modifying the React component once I finally found the file it was in).

Before:
![product title before](https://user-images.githubusercontent.com/26701119/47594254-734b7d80-d948-11e8-8e8e-1a2665160775.jpg)
After: 
![product title after](https://user-images.githubusercontent.com/26701119/47594257-76466e00-d948-11e8-831a-a86035982eda.jpg)

**Comment by Johnsalzarulo** [comment]
This is perfect.

**Comment by PolarisTLX** [comment]
> Also - Just realized I missed one of the deliverables "Hide Hide X button from sidebar" I added it above.
> 
I believe it was there it's just at the end of the task about the search box.

**Comment by PolarisTLX** [comment]
For the new task that Daniel described in Slack: "while you’re in there solo asked for one more tweak to the findify UI— hiding the sort icon on desktop (but keeping on mobile)"

Can you confirm is this is what he wants:

Before:
![sort icon before](https://user-images.githubusercontent.com/26701119/47595303-b0fed500-d94d-11e8-8c61-75ebb1611e42.jpg)

After:
![sort icon after](https://user-images.githubusercontent.com/26701119/47595306-b5c38900-d94d-11e8-89c5-35ae6354a4c2.jpg)

Mobile:
![sort icon mobile](https://user-images.githubusercontent.com/26701119/47595310-bb20d380-d94d-11e8-92ba-fd5492fbe230.jpg)
