### ISSUE TITLE
Research Static Image Hosting Options [3]

### ISSUE THREAD

**Issue by Johnsalzarulo** [withbetterco/guidebook#5]
[This issue over on WellStart](https://github.com/withbetterco/wellstart/issues/1201) made me realize that our strategy for "static assets" (Images + Iconography + Video for Websites) is a bit of a mess. 

As of right now it's all hosted in an AWS account that I only have access too. 

To be clear I am talking about "Static assets" for marketing and user interface, I'm not talking about "user uploaded content" - that's all working fine for us for now. 

Moving forward I need to find a solution or service that possibly enables some better functionality - for example: 

- CDN distribution (Raw AWS does not do this style caching the way that all these companies with "cloud" in their names do) 
- User management - I want to be able to share current assets and have developers on the team be able to add their own. 
- Some kind of "versioning", redundancy or "trash can" so that a single team member can't just hard delete and asset and have it be gone forever. 

It seems like we have a few options by just modifying our internal tooling: 

- Rails Asset Pipeline (Suposedly works out of the box but I've had lots of issues trying to get this to play nice with Heroku, I guess they have made lots of progress in recent years, so we should possibly explore this) 
   - Pros: Built into rails - Free - Nobody has to learn anything extra - assets and versioning is all in the Git repo. 
   - Cons: Potentially no CDN (depending on how we configure it) 

- Gulp File config with a "roll your own" javascript solution - this might not be a bad Idea - Paul and I have had good luck on some recent projects using gulp for JavaScript and CSS compilation. Could be solid for images too. It would be much like rails in that images would live in the repository. 
- Other options? 

Paid services: 
- [Cloudinary](https://cloudinary.com/) - Seems super plug and play and nice, although they tend to push hard to also want to host your "user submitted" content as well. I don't want to depend on a 3rd party service for that though. 
   - Pros: Seems really straightforward and has a lot of advanced functionality, compression, CDN caching. Seems especially nice for video hosting. 
- [Cloudfront](https://aws.amazon.com/cloudfront/) - I guess this somehow goes "in front of" our AWS. I don't know a ton about it but I've heard good things. 
- [Cloudflare](https://www.cloudflare.com/) - This one is a bit extreeme - I've used it in the past. It really does solve the CDN peice of things but to my knoweldge not the actually origin file hosting. It's caching is so agressive that it's hard for me to use it as our sites are constantly changing so much. 
- Other options? 

Take a good 2-3 hours explore some options and let me know your findings - if we need to do some small tests in production we can do so as well. Maybe use the [company website](https://github.com/withbetterco/withbetter) as a testing ground?

**Comment by Johnsalzarulo** [comment]
@iarobinson - FYI - I tested your implementation of using `image_tag` and hosting the images in the asset pipeline on the beta server and I had no issues - this might be the easiest way to start hosting internal images. Just actually use the asset pipeline. 

Maybe combine this with cloudflare it could be bulletproof? I just wanted to give this tidbit to aid you in your research. For now, the images on the getting started page are hosted using the asset_pipeline. We may want to change that depending on your research on this topic.

**Comment by iarobinson** [comment]
This seems like a river to cross when we get there.

Medoplex's design thus far is not asset dense and therefore I don't see the value in researching ways to make it faster.

Is WellStart having issues in production with load speed? As I asked that question, I realized I know how to test that. Here are the results:

## On Mobile

<img width="1180" alt="wellstarthealth mobile audit results" src="https://user-images.githubusercontent.com/7991933/48281924-10a8b600-e40d-11e8-8334-a4d06af345e4.png">

## On Desktop

<img width="1177" alt="wellstarthealth desktop audit results" src="https://user-images.githubusercontent.com/7991933/48281923-10a8b600-e40d-11e8-82d5-34edd18c53c2.png">

## Low Hanging Performance Fruit

<img width="765" alt="screen shot 2018-11-09 at 11 02 04 am" src="https://user-images.githubusercontent.com/7991933/48282672-28813980-e40f-11e8-9b05-00cd12640cba.png">

**Comment by iarobinson** [comment]
Here's a CDN lookup of basecamp. According to this tool, it appears they are _not_ using a CDN.

<img width="541" alt="screen shot 2018-11-09 at 12 01 20 pm" src="https://user-images.githubusercontent.com/7991933/48285360-333fcc80-e417-11e8-86c3-e9094a590750.png">

**Comment by Johnsalzarulo** [comment]
I appreciate the detailed write up and info. I never thought to think of it in terms of our main issues - Site performance vs file organization + history. 

I think I agree with you overall that the asset pipeline is the simplest / best solution. 

That said - I [opened up a new issue](https://github.com/withbetterco/wellstart/issues/1313) to transition all the static assets to the asset pipeline. 

I also opened up [another issue](https://github.com/withbetterco/wellstart/issues/1314) to address the font-awesome performance issue.
